spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: sakthi.via.app@gmail.com
    password: gucitjozlhwwkpsk
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
via:
  countries:
    api:
      url: https://openexchangerates.org/api/currencies.json
  currencyrate:
    api:
      url: https://api.exchangeratesapi.io/latest?base=%s
  rateswithtargets:
    api:
      url: https://api.exchangeratesapi.io/latest?symbols=%s&base=%s