spring:
  datasource:
    url: jdbc:postgres://qaznpaayhzjydd:1a67e2ab4270a4c2a832af0afeeec59f5bc56276d2872dbd40d1ad0094bab824@ec2-54-247-82-14.eu-west-1.compute.amazonaws.com:5432/d5j0ek3vphrub8
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: sakthi.via.app@gmail.com
    password: gucitjozlhwwkpsk
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
via:
  countries:
    api:
      url: https://openexchangerates.org/api/currencies.json
  currencyrate:
    api:
      url: https://api.exchangeratesapi.io/latest?base=%s
  rateswithtargets:
    api:
      url: https://api.exchangeratesapi.io/latest?symbols=%s&base=%s
  scheduler:
    cron:
      value: 0 30 17 ? * MON-FRI
    cache:
      evict:
        value: 600000
  sms:
    twilo:
      phonenumber: +15416124108
      auth:
        token: 931b13a6891249783d03bf5c96c9650c
      account:
        sid: AC3708314765ca28d112fa81ee56492103
logging:
  level:
    org:
      springframework:
        cache: TRACE